import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rohit Parihar - Java Full Stack Developer",
  description: "Generated by create next app",
  icons: {
    icon: "https://media.licdn.com/dms/image/D5635AQGK4NZFvhgKBw/profile-framedphoto-shrink_400_400/0/1717055020459?e=1719075600&v=beta&t=Q6C9k3_yd9LHN4hfbFC6nCAMRbBO8ORQ52LAEwZP0io",
    href: "https://media.licdn.com/dms/image/D5635AQGK4NZFvhgKBw/profile-framedphoto-shrink_400_400/0/1717055020459?e=1719075600&v=beta&t=Q6C9k3_yd9LHN4hfbFC6nCAMRbBO8ORQ52LAEwZP0io"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={"dark"}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
